### ISSUE TITLE
Can't use token wizard with 2FA

### ISSUE THREAD

**Issue by fjl** [magit/ghub#55]
When I try to use `magit-checkout-pull-request`, the token wizard pops up and asks me for my GitHub username and password for `https://api.github.com`. I enter those. Then it prompts again with a different URL `https://api.github.com/authorizations?per_page=100`. I enter the credentials again. Finally the message `ghub--handle-response-error: HTTP Error: 400, "Bad Request", "and Github didn't return JSON"` is displayed.

Checking the ` *http api.github.com:443*` buffer, I can see that GitHub rejected the request because no 2FA code was provided. The code seems to handle 2FA in the `ghub--basic-auth-errorback` function but it's not used in `ghub-create-token`.

**Comment by tarsius** [comment]
I have just pushed two bug fixes. It sounds like what you are describing is another issue, but could you please try again anyway?

**Comment by tarsius** [comment]
I think that's because you entered an incorrect password.

> Then it prompts again with a different URL `https://api.github.com/authorizations?per_page=100`. I enter the credentials again. 

That doesn't actually happen when I use an incorrect password at the first (and in my case only) prompt. That difference could be due to us using different Emacs versions. (What version are you using?)

> Finally the message `ghub--handle-response-error: HTTP Error: 400, "Bad Request", "and Github didn't return JSON"` is displayed.

But that is what happens to me too when I use an incorrect password.

There are a few problems here:

1. Github does not return a proper errror.
2. URL caches the incorrect password.
3. Ghub does not work around these defects.

Because of (2) you have to restart Emacs before trying again.

**Comment by fjl** [comment]
I'm using `GNU Emacs 27.0.50 (build 1, x86_64-apple-darwin17.5.0, NS appkit-1561.40 Version 10.13.4 (Build 17E199)) of 2018-04-03`.

**Comment by fjl** [comment]
I'm sure that the password is correct because I copied it from my password manager.
Just tried again with the latest ghub commit and it still fails in the same way. This time I have
also checked the http buffer in between prompts. For the first request GitHub returns 401 Unauthorized without any content. For the second one the response body is

```text
{"message":"Must specify two-factor authentication OTP code.","documentation_url":"https://developer.github.com/v3/auth#working-with-two-factor-authentication"}
```

**Comment by fjl** [comment]
@jonyamo you can see the buffer by typing `C-x b SPC TAB`. It's a hidden buffer with space as the first character of the buffer name.

**Comment by tarsius** [comment]
@fjl You are now getting a different error then earlier, so you it looks like you "did something wrong" one of these times. Do you know what you are doing differently?

**Comment by tarsius** [comment]
Uh, actually I can reproduce this now... investigating.

**Comment by tarsius** [comment]
Okay I was wrong about the Github API change.

The problem was in a weird implementation detail in `url.el`, which I would say qualifies as a bug.

**Comment by jonyamo** [comment]
Works like a charm 👌 ... thanks for the quick fix @tarsius! And thanks for the info @fjl 👍

**Comment by matthew-piziak** [comment]
Sorry necromance this issue. I'm on `ghub` version 0804a98 (Emacs 26.3) and I'm getting exactly the same error as @jonyamo [here](https://github.com/magit/ghub/issues/55#issuecomment-379790823). It's a strange error, given that I _am_ specifying an OTP code. I've tried multiple times, I don't think I'm fat fingering anything, especially since I'd expect to get a "wrong OTP code" message, or something similarly specific.

**Comment by tarsius** [comment]
Look at the commit which is supposed to fix this. Then investigate how the value of `url-registered-auth-schemes` is affected by this and whether it does so in a way that contradicts what I have said in the commit message.

**Comment by matthew-piziak** [comment]
Will do! Thanks for the response. I'll report back with what I find.

**Comment by marioidival** [comment]
It's not working for me :cry:

**Comment by tarsius** [comment]
Yes, apparently something changed and it doesn't work anymore, see #104.
